.MODEL SMALL
.STACK 100H
.DATA
 
 SMG1 DB 'ENTER FIRST INPUT:$'
 SMG2 DB 'ENTER SECOND INPUT:$'
 SMG3 DB 'SUM = $'
 
.CODE
 MAIN PROC
         
  MOV AX,@DATA
  MOV DS,AX
  
  LEA DX,SMG1  ;DISPLY STRING WHICH IN SMG1
  MOV AH,9
  INT 21H
  
  MOV AH,1  ;TAKE FIRST INPUT
  INT 21H
  
  MOV BL,AL ;MOVE INPUT IN BL REGISTER 
  
  MOV DX,10 ;USE FOR NEW LINE
  MOV AH,2
  INT 21H
  MOV DX,13  ;USE FOR WRITE FROM START
  MOV AH,2
  INT 21H
  
  LEA DX,SMG2  ;DISPLY STRING WHICH IN SMG2
  MOV AH,9
  INT 21H
  
  MOV AH,1  ;TAKE SECOND INPUT
  INT 21H
  
  MOV CL,AL  ;MOVE INPUT IN CL REGISTER
  
  MOV DX,10 ;USE FOR NEW LINE
  MOV AH,2
  INT 21H
  MOV DX,13  ;USE FOR WRITE FROM START
  MOV AH,2
  INT 21H
  
  ADD BL,CL  ;ADD BL AND CL AND SAVE SUM IN BL 
  
  LEA DX,SMG3  ;DISPLY STRING WHICH IN SMG3
  MOV AH,9
  INT 21H
  
  MOV DL,BL  ;BL MOVE SUM IN DL FOR DISPLAY RESULT
  SUB DL,48  ;TO CONVERT ASCII CODE IN NUMBER
  MOV AH,2
  INT 21H
  
  MOV AH,4CH ;TERMINATE PROGRAM
  INT 21H
         
  MAIN ENDP
 END MAIN