.MODEL SMALL
.STACK 100H
.DATA
   
 ARY1 DB 3 DUP('A')  ;HAVE 3 A IN THIS ARRAY
 ARY2 DB 'A','B','C'
 ARY3 DB 3 DUP('?')  ;TAKE 3 INPUT IN THIS ARRAY
   
.CODE
  MAIN PROC
          
   MOV AX,@DATA
   MOV DS,AX
   
   MOV SI,OFFSET ARY1   ;LOAD ARY1 IN SI REGISTER
   MOV DX,[SI]         ;[SI] HOLD ADDRESS AND SEND VALUE TO DX
   MOV AH,2
   INT 21H
   
   MOV SI,OFFSET ARY2
   MOV DX,[SI+1]
   MOV AH,2
   INT 21H 
   
   MOV CX,3
   MOV SI,0
   INPUT:
   MOV AH,1
   INT 21H
   
   MOV ARY3[SI],AL
   INC SI
   LOOP INPUT
   
   MOV SI,OFFSET ARY3
   MOV DX,[SI+2]
   MOV AH,2
   INT 21H
   
   MOV AH,4CH
   INT 21H
    
    MAIN ENDP
  END MAIN